"use client";
import { useState } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const [count, setCount] = useState(0);
  return (
    <html lang="ja">
      <body>
        <h2>Header</h2>
        <button onClick={()=> setCount(count +1)}>+</button>
        <div>{count}</div>
        {children}
      </body>
    </html>
  )
}
