import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Page() {
  return (
    <>
      <h1>Hello!!!, Next.js 13 🐾!!!!!!</h1>
      <Link href="/page1">Page1へ</Link>
    </>
  );
}